name: CDK deploy
description: deploy some cdk
inputs:
  debug:
    required: false
  environment-name:
    required: true
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true
  working-directory:
    required: false
    default: ./
  overlay-artifact:
    required: false
runs:
  using: composite

  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.overlay-artifact }}
    - name: install dependancies
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: debug
      run: ls -la
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: CDK bootstrap
      run: npm run cdk -- bootstrap
      working-directory: ${{ inputs.working-directory }}
      shell: bash
    - name: CDK deploy
      run: >
        npm run cdk -- 
        deploy --require-approval=never -c branch="${{ inputs.environment-name }}"
        -c stack_name="${{ inputs.environment-name }}-${{ github.event.repository.id }}"
        -c stack_description="${{ github.event.repository.html_url }}/tree/${{ inputs.environment-name }}"
        --all
      working-directory: ${{ inputs.working-directory }}
      shell: bash
