name: CDK deploy
description: deploy some cdk
inputs:
  environment_name:
    required: true
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  aws_region:
    required: true
  working-directory:
    required: false
    default: ./
branding:
  icon: upload-cloud
  color: orange
runs:
  using: composite
  steps:
    - name: list
      working-directory: ${{ inputs.working-directory }}
      run: ls -la
      shell: bash
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - name: install dependancies
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
      shell: bash
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
    - name: CDK bootstrap
      working-directory: ${{ inputs.working-directory }}
      run: node_modules/.bin/cdk bootstrap
      shell: bash
    - name: CDK deploy
      working-directory: ${{ inputs.working-directory }}
      run: >
        echo node_modules/.bin/cdk deploy --require-approval=never -c branch="${{ inputs.environment_name }}"
        -c stack_name="${{ inputs.environment_name }}-${{ github.event.repository.id }}"
        -c stack_description="${{ github.event.repository.html_url }}/tree/${{ inputs.environment_name }}"
        --all
      shell: bash
