name: Build next.js app

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      # TODO: assumes the app is in the root directory but might need to accept a working-directory input
      - name: Load app dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace}}/node_modules
          key: ${{ format('node_modules-{0}', hashFiles('package-lock.json')) }}

      # see https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions
      - name: Cache nextjs build dirs
        uses: actions/cache@v3
        with:
          # .next/standalone and next.out are generated when deploying with @sledg/nextjs-lambda
          path: |
            ${{ github.workspace }}/.next
            ${{ github.workspace }}/next.out
          # Generate a new cache whenever packages or source files change.
          key: nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build
        run: |
          npm run build
          if [[ -d node_modules/@sladg/nextjs-lambda ]]; then
            npx --package @sladg/nextjs-lambda next-utils pack
          fi
