name: CDK TBD pipeline
on:
  workflow_call:
    inputs:
      download_artifact:
        required: false
        type: string
      download_artifact_path:
        default: build
        required: false
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
      aws_region:
        required: true

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.download_artifact }}
      - uses: clear-treasury/github-actions/actions/cdk-deploy@deploy-rework
        with:
          aws_access_key_id: ${{ secrets.aws_access_key_id }}
          aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
          aws_region: ${{ secrets.aws_region }}
          working-directory: ./
          environment_name: dev

  integration-test:
    name: integration test
    needs:
      - deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: integration test cmd
        run: |
          ls -la
          touch integration-test

  deploy-prod:
    needs:
      - integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download build
        uses: actions/download-artifact@v3
        with:
          name: build-prod
          path: ./build
      - name: deploy cmd
        run: |
          ls -la
          test -f ./build/build-prod
          test -f working-prod
          touch deploy-prod

  check:
    needs:
      - deploy-dev
      - deploy-prod
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: slack us for dev
        run: |
          echo "slack us"
          echo '${{ toJSON(job) }}'
