name: CDK TBD pipeline
on:
  workflow_call:
    secrets:
      prod-aws-access-key-id:
        required: true
      prod-aws-secret-access-key:
        required: true
      prod-aws-region:
        required: true

      nonprod-aws-access-key-id:
        required: true
      nonprod-aws-secret-access-key:
        required: true
      nonprod-aws-region:
        required: true
    inputs:
      download-artifact:
        required: false
        type: string
      download-artifact-path:
        default: build
        required: false
        type: string
      working-directory:
        required: false
        type: string
        default: .

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test-check
        run: test -f test.sh && echo "::set-output name=present::aaah" || echo "::set-output name=present::false"
      - name: test-check-debug
        run: test -f test.sh
      - name: test cmd
        if: steps.test-check.outputs.present == 'aaah'
        run: test.sh

  deploy-dev:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: clear-treasury/github-actions/actions/cdk-deploy@deploy-rework
        with:
          aws-access-key-id: ${{ secrets.nonprod-aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.nonprod-aws-secret-access-key }}
          aws-region: ${{ secrets.nonprod-aws-region }}
          working-directory: ${{ inputs.working-directory }}
          environment-name: dev

  integration-test:
    name: integration test
    needs:
      - deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: integration-test-check
        run: |
          echo -n "::set-output name=present::"
          test -f integration_test.sh && echo "true" || echo "false"
      - run: |
          test -f integration_test.sh && echo "true" || echo "false"
      - name: integration test cmd
        if: steps.integration-test-check.outputs.present == true
        run: integration_test.sh

  deploy-prod:
    needs:
      - integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: clear-treasury/github-actions/actions/cdk-deploy@deploy-rework
        with:
          aws-access-key-id: ${{ secrets.prod-aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.prod-aws-secret-access-key }}
          aws-region: ${{ secrets.prod-aws-region }}
          working-directory: ${{ inputs.working-directory }}
          environment-name: main

  notify-failure:
    needs:
      - deploy-dev
      - deploy-prod
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: slack us for dev
        run: |
          echo "slack us"
          echo '${{ toJSON(job) }}'
