name: CDK TBD pipeline
on:
  workflow_call:
    inputs:
      download_artifact:
        required: false
        type: string
      download_artifact_path:
        default: build
        required: false
        type: string

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      environment_name: dev
    steps:
      - uses: clear-treasury/github-actions/actions/cdk-deploy@deploy-rework
        with:
          aws_access_key_id: ${{ secrets.NONPROD_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.NONPROD_AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.NONPROD_AWS_DEFAULT_REGION }}
          working-directory: ./
          environment_name: dev

  integration-test:
    name: integration test
    needs:
      - deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: integration test cmd
        run: |
          ls -la
          touch integration-test

  deploy-prod:
    needs:
      - integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.download_artifact }}
      - uses: clear-treasury/github-actions/actions/cdk-deploy@deploy-rework
        with:
          aws_access_key_id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          # broken as nonprod on purpose
          aws_secret_access_key: ${{ secrets.NONPROD_AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.PROD_AWS_DEFAULT_REGION }}
          working-directory: ./
          environment_name: dev

  check:
    needs:
      - deploy-dev
      - deploy-prod
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: slack us for dev
        run: |
          echo "slack us"
          echo '${{ toJSON(job) }}'
