name: Deploy CDK app

on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Load app dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('../package-lock.json') }}

      - name: Load infra dependencies
        uses: actions/cache@v3
        with:
          path: infra/node_modules
          key: infra-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Load nextjs build
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}

      - name: Load next.out directory
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/next.out
          key: ${{ runner.os }}-next.out-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Deploy
        run: |
          npm run cdk bootstrap
          npm run cdk deploy -- --all --require-approval=never \
            -c stack_name="${{ github.ref_name }}-${{ github.event.repository.id }}" \
            -c stack_description="${{ github.event.repository.html_url }}/tree/${{ github.ref_name }}"
