name: Lint files

on:
  workflow_call:
    inputs:
      working-directory:
        description: "The directory name in which to run lint. Defaults to root"
        default: ""
        required: false
        type: string
      package-manager:
        description: "The packager manager with which to run lint. Defaults to npm"
        default: "npm"
        required: false
        type: string      

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory || github.workspace }}

    env:
      PATH_PREFIX: ${{ inputs.working-directory && format('{0}/{1}', github.workspace, inputs.working-directory) || github.workspace }}
      CACHE_PREFIX: ${{ inputs.working-directory && format('{0}-', inputs.working-directory) || '' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pnpm
        if: inputs.package-manager == 'pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node
        if: inputs.package-manager == 'npm'
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ${{ env.PATH_PREFIX }}/package-lock.json

      - name: Setup node
        if: inputs.package-manager == 'pnpm'
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: ${{ env.PATH_PREFIX }}/pnpm-lock.yaml

      - name: Load dependencies
        if: inputs.package-manager == 'npm'
        uses: actions/cache@v3
        with:
          path: ${{ env.PATH_PREFIX }}/node_modules
          key: ${{ format('{0}node_modules-{1}', env.CACHE_PREFIX, hashFiles(format('{0}/package-lock.json', env.PATH_PREFIX))) }}

      - name: Load dependencies
        if: inputs.package-manager == 'pnpm'
        uses: actions/cache@v3
        with:
          path: ${{ env.PATH_PREFIX }}/node_modules
          key: ${{ format('{0}node_modules-{1}', env.CACHE_PREFIX, hashFiles(format('{0}/pnpm-lock.yaml', env.PATH_PREFIX))) }}

      - name: Lint
        if: inputs.package-manager == 'npm'
        run: npm run lint

      - name: Lint
        if: inputs.package-manager == 'pnpm'
        run: pnpm run lint
